import { 
  CategoryInfo, 
  ComplaintTicket, 
  DepartmentGatekeeperConfig, 
  GrievanceCategory, 
  NotificationItem 
} from './types';

export const CATEGORY_DEFINITIONS: Record<GrievanceCategory, CategoryInfo> = {
  HR: {
    key: 'HR',
    nameTh: 'ทรัพยากรบุคคลและสวัสดิการ (HR)',
    nameEn: 'Human Resources & Benefits',
    descriptionTh: 'ค่าตอบแทน สวัสดิการ เวลาการทำงาน การโยกย้ายตำแหน่ง และความสัมพันธ์แรงงาน',
    responsibleDept: 'People & Culture Department (ฝ่ายบริหารทรัพยากรบุคคล)',
    badgeColor: 'bg-blue-50 text-blue-700 border-blue-200',
    iconName: 'Users',
  },
  IT: {
    key: 'IT',
    nameTh: 'ระบบสารสนเทศและเทคโนโลยี (IT)',
    nameEn: 'Information Technology & Systems',
    descriptionTh: 'ฮาร์ดแวร์ ซอฟต์แวร์ เน็ตเวิร์ก ความปลอดภัยทางไซเบอร์ และสิทธิ์การเข้าถึงระบบ',
    responsibleDept: 'Digital Technology & Enterprise IT (ฝ่ายเทคโนโลยีสารสนเทศ)',
    badgeColor: 'bg-cyan-50 text-cyan-700 border-cyan-200',
    iconName: 'Laptop',
  },
  Safety: {
    key: 'Safety',
    nameTh: 'ความปลอดภัยและชีวอนามัย (Safety)',
    nameEn: 'Occupational Health & Safety (EHS)',
    descriptionTh: 'สภาพแวดล้อมเสี่ยงอันตราย อุปกรณ์ป้องกันภัย (PPE) อุบัติเหตุ และความปลอดภัยในอาคาร/โรงงาน',
    responsibleDept: 'Occupational Health & Safety Office (ฝ่ายความปลอดภัยและอาชีวอนามัย)',
    badgeColor: 'bg-amber-50 text-amber-700 border-amber-200',
    iconName: 'ShieldAlert',
  },
  Compliance: {
    key: 'Compliance',
    nameTh: 'การกำกับการปฏิบัติตามกฎเกณฑ์ (Compliance)',
    nameEn: 'Regulatory & Corporate Compliance',
    descriptionTh: 'การไม่ปฏิบัติตามกฎหมาย นโยบายบริษัท ข้อบังคับ PDPA หรือมาตรฐานอุตสาหกรรม',
    responsibleDept: 'Governance, Risk & Compliance Division (ฝ่ายกำกับดูแลและกฎหมาย)',
    badgeColor: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    iconName: 'FileCheck2',
  },
  Ethics: {
    key: 'Ethics',
    nameTh: 'จริยธรรมและธรรมาภิบาล (Ethics)',
    nameEn: 'Corporate Ethics & Code of Conduct',
    descriptionTh: 'ผลประโยชน์ทับซ้อน ความโปร่งใส ความเป็นธรรม และจรรยาบรรณวิชาชีพ',
    responsibleDept: 'Ethics Committee & Internal Governance (คณะกรรมการจริยธรรมองค์กร)',
    badgeColor: 'bg-purple-50 text-purple-700 border-purple-200',
    iconName: 'Scale',
  },
  Harassment: {
    key: 'Harassment',
    nameTh: 'การคุกคามและการเลือกปฏิบัติ (Harassment)',
    nameEn: 'Anti-Harassment & Discrimination',
    descriptionTh: 'การกลั่นแกล้ง คุกคามทางเพศ วาจาไม่เหมาะสม หรือการเลือกปฏิบัติอย่างไม่เป็นธรรม',
    responsibleDept: 'Employee Grievance & Whistleblower Panel (คณะกรรมการคุ้มครองสิทธิพนักงาน)',
    badgeColor: 'bg-rose-50 text-rose-700 border-rose-200',
    iconName: 'AlertOctagon',
  },
  Fraud: {
    key: 'Fraud',
    nameTh: 'การทุจริตและการฉ้อโกง (Fraud)',
    nameEn: 'Fraud & Financial Misconduct',
    descriptionTh: 'การยักยอกเงิน การทุจริตจัดซื้อ จัดจ้าง เอกสารเท็จ หรือการรับสินบน',
    responsibleDept: 'Internal Audit & Forensic Investigation (ฝ่ายตรวจสอบภายในและการสอบสวน)',
    badgeColor: 'bg-red-50 text-red-700 border-red-200',
    iconName: 'FileWarning',
  },
  Quality: {
    key: 'Quality',
    nameTh: 'คุณภาพสินค้าและบริการ (Quality)',
    nameEn: 'Quality Assurance & Service Standards',
    descriptionTh: 'ข้อบกพร่องของกระบวนการทำงาน การส่งมอบงานตกหล่น หรือมาตรฐานบริการที่ไม่ได้เกณฑ์',
    responsibleDept: 'Operational Excellence & Quality Assurance (ฝ่ายประกันคุณภาพและการปรับปรุง)',
    badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    iconName: 'CheckCircle2',
  },
  Environment: {
    key: 'Environment',
    nameTh: 'สิ่งแวดล้อมและความยั่งยืน (Environment)',
    nameEn: 'Environment, Energy & ESG',
    descriptionTh: 'การจัดการขยะ/ของเสีย การใช้พลังงานสิ้นเปลือง มลพิษทางอากาศ/น้ำ และการปล่อยคาร์บอน',
    responsibleDept: 'Sustainability & Environmental Safety Team (ฝ่ายความยั่งยืนและสิ่งแวดล้อม ESG)',
    badgeColor: 'bg-teal-50 text-teal-700 border-teal-200',
    iconName: 'Leaf',
  },
};

export const INITIAL_COMPLAINTS: ComplaintTicket[] = [
  {
    id: 'tk-1',
    trackingCode: 'TK-2026-0881',
    type: 'complaint',
    category: 'IT',
    title: 'ระบบ VPN และเครือข่ายสำนักงานชั้น 18 ตัดการเชื่อมต่อบ่อยครั้งกระทบการประชุมกับลูกค้าต่างประเทศ',
    description: 'ในช่วง 2 สัปดาห์ที่ผ่านมา สัญญาณ Wi-Fi และ Gateway VPN ในโซน Open Space ชั้น 18 อาคาร B มีอาการหลุดทุก 20 นาที ทำให้ทีมงานไม่สามารถประชุม Virtual Pitch กับลูกค้าได้ตามกำหนด',
    locationOrUnit: 'อาคาร B ชั้น 18 โซน Enterprise Solutions',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'ณภัทร วัฒนโกสินทร์',
    submitterEmployeeId: 'EMP-4092',
    submitterDepartment: 'Enterprise Solutions Group',
    submitterEmail: 'naphat.w@company.internal',
    submitterPhone: '081-445-9988',
    gatekeeperDepartment: 'Digital Technology & Enterprise IT',
    assignedOfficerName: 'กิตติศักดิ์ ชัยชนะ (Lead Network Engineer)',
    assignedOfficerEmail: 'kittisak.c@company.internal',
    slaTargetHours: 24,
    slaDueDate: '2026-08-28T18:00:00.000Z',
    slaStatus: 'on_track',
    status: 'in_progress',
    urgency: 'High',
    riskSeverity: 'Moderate',
    sentiment: 'Frustrated',
    clusterGroup: 'IT Infrastructure & Network Stability',
    rootCauseCategory: 'Equipment/Tools',
    rootCauseSummary: 'Access Point Firmware เก่าและโหลด Balancing เกินพิกัดช่วง 10:00 - 15:00',
    preventiveActionPlan: 'อัปเกรด Cisco Core AP เป็น Wi-Fi 6 และเพิ่มกระจายช่องสัญญาณ',
    attachments: [
      { id: 'att-1', name: 'ping_packet_loss_log_ch18.pdf', size: '1.2 MB', type: 'application/pdf' },
      { id: 'att-2', name: 'speedtest_screenshot.png', size: '480 KB', type: 'image/png' },
    ],
    timeline: [
      {
        id: 'tl-1',
        timestamp: '2026-08-27T09:15:00.000Z',
        actor: 'ณภัทร วัฒนโกสินทร์',
        actorRole: 'Employee',
        action: 'ส่งเรื่องเข้าระบบสำเร็จ',
        status: 'submitted',
        notes: 'บันทึกคำร้องพร้อมแนบผลทดสอบสัญญาณ',
      },
      {
        id: 'tl-2',
        timestamp: '2026-08-27T10:30:00.000Z',
        actor: 'IT Helpdesk Gatekeeper Team',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและคัดกรองความเร่งด่วน',
        status: 'gatekeeper_triaged',
        notes: 'ตรวจสอบผลกระทบ พบว่ามีพนักงานในโซนได้รับผลกระทบกว่า 45 คน จัดระดับความเร่งด่วนเป็น High และส่งต่อวิศวกรโครงข่าย',
      },
      {
        id: 'tl-3',
        timestamp: '2026-08-27T13:00:00.000Z',
        actor: 'กิตติศักดิ์ ชัยชนะ',
        actorRole: 'Assigned Officer',
        action: 'เริ่มกระบวนการตรวจสอบและแก้ไขทางเทคนิค',
        status: 'in_progress',
        notes: 'ลงพื้นที่ตรวจจับค่า Packet Collision ที่ Switch ชั้น 18 และจัดเตรียม Config AP ใหม่เพื่อลดการชนกันของคลื่น',
      },
    ],
    createdAt: '2026-08-27T09:15:00.000Z',
    updatedAt: '2026-08-27T13:00:00.000Z',
  },
  {
    id: 'tk-2',
    trackingCode: 'TK-2026-0880',
    type: 'complaint',
    category: 'Safety',
    title: 'บันไดหนีไฟทางทิศตะวันออกมีกล่องพัสดุและพาเลทไม้กีดขวางทางออกฉุกเฉิน',
    description: 'พบพาเลทสินค้าจากผู้รับเหมาวางกองสะสมปิดทางออกประตูหนีไฟชั้น 2 โกดังสินค้า A ซึ่งหากเกิดเพลิงไหม้จะไม่สามารถผลักประตูหนีไฟออกได้ตามมาตรฐานความปลอดภัย',
    locationOrUnit: 'โกดังสินค้ากลาง A ชั้น 2 ประตูหนีไฟทิศตะวันออก',
    isDirectToExecutive: true,
    confidentiality: 'standard_named',
    submitterName: 'ปวีณา อุดมทรัพย์',
    submitterEmployeeId: 'EMP-3120',
    submitterDepartment: 'Logistics & Supply Chain Operations',
    submitterEmail: 'paweena.u@company.internal',
    gatekeeperDepartment: 'Occupational Health & Safety Office',
    assignedOfficerName: 'จ่าเอก วีระยุทธ พงษ์ศิริ (EHS Manager)',
    assignedOfficerEmail: 'weerayuth.p@company.internal',
    slaTargetHours: 12,
    slaDueDate: '2026-08-27T22:00:00.000Z',
    slaStatus: 'met',
    status: 'resolved',
    urgency: 'Critical',
    riskSeverity: 'High',
    sentiment: 'Urgent',
    clusterGroup: 'Factory & Warehouse EHS Compliance',
    rootCauseCategory: 'Process',
    rootCauseSummary: 'ผู้รับเหมาภายนอกไม่มีพื้นที่พักของชั่วคราวและขาดเจ้าหน้าที่ รปภ. กำกับดูแลจุดหนีไฟ',
    preventiveActionPlan: 'กำหนดจุดวางพักสินค้าชั่วคราวพร้อมตีเส้นสีเหลือง-ดำ ห้ามวางของกีดขวางประตูฉุกเฉินทุกกรณี',
    resolutionSummary: 'เจ้าหน้าที่ EHS และทีม รปภ. ได้เข้าทำการเคลื่อนย้ายพาเลทและสิ่งกีดขวางทั้งหมดออกเรียบร้อยแล้ว ตรวจสอบระบบล็อคหนีไฟพร้อมใช้งาน 100% และตักเตือนผู้รับเหมาเป็นลายลักษณ์อักษร',
    resolvedAt: '2026-08-27T15:45:00.000Z',
    attachments: [
      { id: 'att-3', name: 'blocked_emergency_exit_photo.jpg', size: '2.4 MB', type: 'image/jpeg' },
      { id: 'att-4', name: 'cleared_emergency_exit_verified.jpg', size: '1.8 MB', type: 'image/jpeg' },
    ],
    timeline: [
      {
        id: 'tl-21',
        timestamp: '2026-08-27T10:00:00.000Z',
        actor: 'ปวีณา อุดมทรัพย์',
        actorRole: 'Employee',
        action: 'ส่งเรื่องด่วนตรงถึงผู้บริหารและ Safety Officer',
        status: 'submitted',
        notes: 'ติ๊กส่งตรงถึงผู้บริหาร CEO/EVP เนื่องจากเป็นความปลอดภัยในชีวิต',
      },
      {
        id: 'tl-22',
        timestamp: '2026-08-27T10:15:00.000Z',
        actor: 'EHS Gatekeeper Automation',
        actorRole: 'System',
        action: 'แจ้งเตือนอัตโนมัติถึงฝ่ายบริหารและหัวหน้า EHS ทันที',
        status: 'gatekeeper_triaged',
        notes: 'ระบบส่ง SMS & LINE Notification แจ้งเคสระดับ Critical ให้ EHS Manager',
      },
      {
        id: 'tl-23',
        timestamp: '2026-08-27T11:00:00.000Z',
        actor: 'จ่าเอก วีระยุทธ พงษ์ศิริ',
        actorRole: 'Assigned Officer',
        action: 'ส่งทีมเคลียร์พื้นที่ฉุกเฉิน',
        status: 'in_progress',
        notes: 'สั่งการ รปภ. และผู้รับเหมาขนย้ายพาเลทออกทันที',
      },
      {
        id: 'tl-24',
        timestamp: '2026-08-27T15:45:00.000Z',
        actor: 'จ่าเอก วีระยุทธ พงษ์ศิริ',
        actorRole: 'Assigned Officer',
        action: 'แก้ไขเสร็จสิ้นและแนบหลักฐานการตรวจสอบ',
        status: 'resolved',
        notes: 'พื้นที่ปลอดสิ่งกีดขวาง 100% พร้อมขอให้ผู้ร้องเรียนประเมินความพึงพอใจ',
      },
    ],
    createdAt: '2026-08-27T10:00:00.000Z',
    updatedAt: '2026-08-27T15:45:00.000Z',
  },
  {
    id: 'tk-3',
    trackingCode: 'TK-2026-0879',
    type: 'suggestion',
    category: 'HR',
    title: 'ข้อเสนอแนะ: จัดตั้งโปรแกรม Flexible Benefits และวันลาเพื่อสุขภาพจิต (Mental Health Day)',
    description: 'เสนอให้ฝ่าย HR เพิ่มความยืดหยุ่นในแพ็กเกจสวัสดิการ เช่น นำวงเงินค่ารักษาพยาบาลคงเหลือไปแลกเป็นคอร์สฟิตเนส หรือการตรวจสุขภาพเฉพาะทาง และเพิ่มวันลา Mental Wellness 2 วันต่อปี',
    locationOrUnit: 'ทุกหน่วยงาน (Corporate-wide)',
    isDirectToExecutive: true,
    confidentiality: 'standard_named',
    submitterName: 'ชลธิชา รัตนไพบูลย์',
    submitterEmployeeId: 'EMP-1823',
    submitterDepartment: 'Strategic Marketing & Brand',
    submitterEmail: 'chonticha.r@company.internal',
    gatekeeperDepartment: 'People & Culture Department',
    assignedOfficerName: 'ภานุมาศ สัจจาภิรมย์ (Head of Total Rewards)',
    assignedOfficerEmail: 'panumas.s@company.internal',
    slaTargetHours: 72,
    slaDueDate: '2026-08-30T17:00:00.000Z',
    slaStatus: 'met',
    status: 'closed',
    urgency: 'Medium',
    riskSeverity: 'Low',
    sentiment: 'Constructive',
    clusterGroup: 'Employee Wellbeing & Benefits Enhancement',
    rootCauseCategory: 'Policy/Governance',
    rootCauseSummary: 'สวัสดิการเดิมเป็นแบบตายตัว ไม่ตอบโจทย์ความหลากหลายของช่วงวัยพนักงาน',
    preventiveActionPlan: 'บรรจุเข้าสู่วาระพิจารณาแผนสวัสดิการประจำปี 2027 และนำร่องโครงการ Flexible Points ใน Q1',
    resolutionSummary: 'ฝ่ายบริหารและ HR พิจารณาเห็นชอบในหลักการ โดยจะเริ่มนำร่องระบบ Flex-Points ในไตรมาสที่ 1 ปีหน้า และอนุมัติวัน Wellness Leave เพิ่มเติม 1 วันในนโยบายใหม่',
    resolvedAt: '2026-08-25T14:30:00.000Z',
    closedAt: '2026-08-26T09:00:00.000Z',
    evaluation: {
      id: 'eval-1',
      ticketId: 'tk-3',
      overallScore: 5,
      speedRating: 5,
      resolutionQualityRating: 5,
      serviceMannerRating: 5,
      clarityRating: 5,
      isResolvedPermanently: true,
      feedbackComment: 'ประทับใจมากที่ฝ่ายบริหารและ HR นำข้อเสนอแนะของพนักงานไปพิจารณาปรับใช้อย่างเป็นรูปธรรมและรวดเร็ว ขอบคุณที่เปิดรับฟังเสียงพนักงานค่ะ',
      improvementSuggestions: 'อยากให้มีการอัปเดตความคืบหน้าระบบ Flex-Points ผ่าน Townhall ครั้งต่อไปด้วยค่ะ',
      evaluatedAt: '2026-08-26T09:00:00.000Z',
    },
    attachments: [
      { id: 'att-5', name: 'flexible_benefits_benchmark_proposal.pdf', size: '3.1 MB', type: 'application/pdf' },
    ],
    timeline: [
      {
        id: 'tl-31',
        timestamp: '2026-08-22T10:00:00.000Z',
        actor: 'ชลธิชา รัตนไพบูลย์',
        actorRole: 'Employee',
        action: 'ยื่นข้อเสนอแนะเพื่อการพัฒนาองค์กร',
        status: 'submitted',
      },
      {
        id: 'tl-32',
        timestamp: '2026-08-22T14:00:00.000Z',
        actor: 'HR Gatekeeper',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและส่งต่อฝ่ายสิทธิประโยชน์',
        status: 'gatekeeper_triaged',
      },
      {
        id: 'tl-33',
        timestamp: '2026-08-24T09:00:00.000Z',
        actor: 'ภานุมาศ สัจจาภิรมย์',
        actorRole: 'Assigned Officer',
        action: 'นำเสนอในที่ประชุม HR Strategy Committee',
        status: 'in_progress',
      },
      {
        id: 'tl-34',
        timestamp: '2026-08-25T14:30:00.000Z',
        actor: 'ภานุมาศ สัจจาภิรมย์',
        actorRole: 'Assigned Officer',
        action: 'แจ้งผลการอนุมัติและแนวทางดำเนินการ',
        status: 'resolved',
      },
      {
        id: 'tl-35',
        timestamp: '2026-08-26T09:00:00.000Z',
        actor: 'ชลธิชา รัตนไพบูลย์',
        actorRole: 'Employee',
        action: 'ประเมินความพึงพอใจ 5 ดาว และปิดเรื่อง',
        status: 'closed',
      },
    ],
    createdAt: '2026-08-22T10:00:00.000Z',
    updatedAt: '2026-08-26T09:00:00.000Z',
  },
  {
    id: 'tk-4',
    trackingCode: 'TK-2026-0878',
    type: 'complaint',
    category: 'Harassment',
    title: 'การใช้คำพูดคุกคามและข่มขู่ในช่องสื่อสารกลุ่มงาน',
    description: 'หัวหน้างานระดับกลางใช้ถ้อยคำดูถูกเหยียดหยามและข่มขู่ตัดโบนัสพนักงานต่อหน้าสมาชิกในทีมกว่า 20 คนในแชตกลุ่มงาน สร้างบรรยากาศหวาดกลัวและกระทบต่อสภาพจิตใจของทีม',
    locationOrUnit: 'แผนก Regional Operations สาขาภาคตะวันออก',
    isDirectToExecutive: true,
    confidentiality: 'standard_named',
    submitterName: 'จิรภัทร ชาญวิทย์',
    submitterEmployeeId: 'EMP-3890',
    submitterDepartment: 'Regional Operations',
    submitterEmail: 'jiraphat.c@company.internal',
    gatekeeperDepartment: 'Employee Grievance & Whistleblower Panel',
    assignedOfficerName: 'นิติกรอาวุโส มนตรี ธนบดีกุล (Legal & HR Compliance)',
    assignedOfficerEmail: 'montri.t@company.internal',
    slaTargetHours: 24,
    slaDueDate: '2026-08-28T12:00:00.000Z',
    slaStatus: 'on_track',
    status: 'in_progress',
    urgency: 'High',
    riskSeverity: 'Severe',
    sentiment: 'Frustrated',
    clusterGroup: 'Workplace Psychological Safety & Ethics',
    rootCauseCategory: 'People',
    rootCauseSummary: 'ภาวะผู้นำบกพร่องและขาดความเข้าใจเรื่อง Anti-Bullying / Harassment Code of Conduct',
    preventiveActionPlan: 'แต่งตั้งคณะกรรมการสอบข้อเท็จจริงอิสระและจัดคอร์ส Mandatory Respectful Leadership',
    attachments: [
      { id: 'att-6', name: 'chat_export_redacted.pdf', size: '950 KB', type: 'application/pdf' },
    ],
    timeline: [
      {
        id: 'tl-41',
        timestamp: '2026-08-26T16:00:00.000Z',
        actor: 'พนักงาน (ไม่เปิดเผยตัวตน)',
        actorRole: 'Employee',
        action: 'ส่งเรื่องร้องเรียนแบบปกปิดตัวตนพิเศษ',
        status: 'submitted',
        notes: 'เลือกช่องทางส่งตรงถึงผู้บริหารระดับสูง CEO/EVP เพื่อความปลอดภัย',
      },
      {
        id: 'tl-42',
        timestamp: '2026-08-26T17:00:00.000Z',
        actor: 'Whistleblower Triage Committee',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและเปิดรหัสสืบสวนลับ',
        status: 'gatekeeper_triaged',
        notes: 'เข้ารหัสข้อมูลผู้ร้องเรียนและมอบหมายนิติกรอาวุโสเป็นผู้รับผิดชอบเดี่ยว',
      },
      {
        id: 'tl-43',
        timestamp: '2026-08-27T08:30:00.000Z',
        actor: 'มนตรี ธนบดีกุล',
        actorRole: 'Assigned Officer',
        action: 'เริ่มกระบวนการสอบข้อเท็จจริงเบื้องต้น',
        status: 'in_progress',
        notes: 'นัดสัมภาษณ์พยานบุคคลแยกห้องปิด และประสานฝ่ายบุคคลเพื่อพิจารณาการย้ายสายการบังคับบัญชาชั่วคราว',
      },
    ],
    createdAt: '2026-08-26T16:00:00.000Z',
    updatedAt: '2026-08-27T08:30:00.000Z',
  },
  {
    id: 'tk-5',
    trackingCode: 'TK-2026-0877',
    type: 'complaint',
    category: 'Environment',
    title: 'ระบบปรับอากาศปล่อยน้ำรั่วซึมลงแปลงคัดแยกขยะรีไซเคิล และเปิดแอร์ทิ้งไว้ช่วงวันหยุด',
    description: 'พบระบบชิลเลอร์ชั้น 4 มีน้ำหยดลงจุดเก็บกล่องกระดาษรีไซเคิลทำให้เน่าเสีย และมีการเปิดเครื่องปรับอากาศทิ้งไว้ในวันเสาร์-อาทิตย์โดยไม่มีการใช้งาน เป็นการสิ้นเปลืองพลังงานขัดต่อนโยบาย ESG',
    locationOrUnit: 'อาคารนวัตกรรม C ชั้น 4',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'ธีรดนย์ สิริพงษ์',
    submitterEmployeeId: 'EMP-5531',
    submitterDepartment: 'Facilities & ESG Sustainability',
    submitterEmail: 'teeradon.s@company.internal',
    gatekeeperDepartment: 'Sustainability & Environmental Safety Team',
    assignedOfficerName: 'ช่างเทคนิค พงศธร เกษมสุข',
    assignedOfficerEmail: 'pongsathorn.k@company.internal',
    slaTargetHours: 48,
    slaDueDate: '2026-08-28T10:00:00.000Z',
    slaStatus: 'on_track',
    status: 'in_progress',
    urgency: 'Medium',
    riskSeverity: 'Low',
    sentiment: 'Concerned',
    clusterGroup: 'Energy Conservation & Facility Maintenance',
    rootCauseCategory: 'Equipment/Tools',
    rootCauseSummary: 'ท่อระบายน้ำทิ้งคอยล์เย็นอุดตัน และ Timer ระบบ Building Automation System (BAS) รีเซ็ตค่าหลังไฟตก',
    preventiveActionPlan: 'ล้างท่อระบายน้ำและตั้งค่าระบบตั้งเวลาอัตโนมัติบน Cloud BAS',
    attachments: [
      { id: 'att-7', name: 'water_leak_chiller4.jpg', size: '1.5 MB', type: 'image/jpeg' },
    ],
    timeline: [
      {
        id: 'tl-51',
        timestamp: '2026-08-26T10:00:00.000Z',
        actor: 'ธีรดนย์ สิริพงษ์',
        actorRole: 'Employee',
        action: 'ส่งเรื่องแจ้งข้อบกพร่องสิ่งแวดล้อม',
        status: 'submitted',
      },
      {
        id: 'tl-52',
        timestamp: '2026-08-26T11:30:00.000Z',
        actor: 'ESG Gatekeeper',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและประสานงานทีมช่างอาคาร',
        status: 'gatekeeper_triaged',
      },
      {
        id: 'tl-53',
        timestamp: '2026-08-26T14:00:00.000Z',
        actor: 'พงศธร เกษมสุข',
        actorRole: 'Assigned Officer',
        action: 'เข้าตรวจสอบท่อแอร์และปรับแก้โปรแกรม BAS',
        status: 'in_progress',
      },
    ],
    createdAt: '2026-08-26T10:00:00.000Z',
    updatedAt: '2026-08-26T14:00:00.000Z',
  },
  {
    id: 'tk-6',
    trackingCode: 'TK-2026-0876',
    type: 'complaint',
    category: 'Fraud',
    title: 'ข้อสงสัยเกี่ยวกับการเสนอราคาคู่เทียบในการจัดซื้ออุปกรณ์ฮาร์ดแวร์พิเศษ',
    description: 'ตรวจพบว่าใบเสนอราคา 3 บริษัทคู่เทียบมีที่อยู่จดทะเบียนและเบอร์โทรศัพท์เดียวกัน มีแนวโน้มเป็นการจัดฮั้วประมูลเพื่อหลีกเลี่ยงเกณฑ์การตรวจสอบราคากลาง',
    locationOrUnit: 'ฝ่ายจัดซื้อและสัญญา (Procurement)',
    isDirectToExecutive: true,
    confidentiality: 'standard_named',
    submitterName: 'วรัญญู พรหมประสิทธิ์',
    submitterEmployeeId: 'EMP-2914',
    submitterDepartment: 'ฝ่ายจัดซื้อและสัญญา (Procurement)',
    submitterEmail: 'waranyu.p@company.internal',
    gatekeeperDepartment: 'Internal Audit & Forensic Investigation',
    assignedOfficerName: 'วรพจน์ ปิยะปัญญา (Director of Forensic Audit)',
    assignedOfficerEmail: 'worapoj.p@company.internal',
    slaTargetHours: 24,
    slaDueDate: '2026-08-27T18:00:00.000Z',
    slaStatus: 'on_track',
    status: 'in_progress',
    urgency: 'Critical',
    riskSeverity: 'Severe',
    sentiment: 'Urgent',
    clusterGroup: 'Procurement Integrity & Anti-Corruption',
    rootCauseCategory: 'Policy/Governance',
    rootCauseSummary: 'ขาดระบบตรวจสอบความเชื่อมโยงของผู้ถือหุ้นบริษัทคู่เทียบอัตโนมัติในกระบวนการ Vendor Onboarding',
    preventiveActionPlan: 'เชื่อมต่อ API กรมพัฒนาธุรกิจการค้า (DBD) เพื่อตรวจเช็ค Cross-Shareholding อัตโนมัติ',
    attachments: [
      { id: 'att-8', name: 'procurement_quotations_evidence.pdf', size: '4.5 MB', type: 'application/pdf' },
    ],
    timeline: [
      {
        id: 'tl-61',
        timestamp: '2026-08-25T11:00:00.000Z',
        actor: 'ผู้แจ้งเบาะแสไม่ประสงค์ออกนาม',
        actorRole: 'Employee',
        action: 'แจ้งเบาะแสการทุจริตผ่าน Whistleblowing Portal',
        status: 'submitted',
        notes: 'ส่งตรงถึงบอร์ดบริหารและผู้อำนวยการฝ่ายตรวจสอบภายใน',
      },
      {
        id: 'tl-62',
        timestamp: '2026-08-25T11:30:00.000Z',
        actor: 'Internal Audit Gatekeeper',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและกำหนดมาตรการคุ้มครองพยาน',
        status: 'gatekeeper_triaged',
      },
      {
        id: 'tl-63',
        timestamp: '2026-08-25T14:00:00.000Z',
        actor: 'วรพจน์ ปิยะปัญญา',
        actorRole: 'Assigned Officer',
        action: 'อายัดเอกสารการจัดซื้อและเริ่มการตรวจสอบเชิงลึก',
        status: 'in_progress',
      },
    ],
    createdAt: '2026-08-25T11:00:00.000Z',
    updatedAt: '2026-08-25T14:00:00.000Z',
  },
  {
    id: 'tk-7',
    trackingCode: 'TK-2026-0875',
    type: 'complaint',
    category: 'Quality',
    title: 'คู่มือการทำงาน (SOP) ในสายการผลิตไลน์ 3 ข้อมูลไม่ตรงกับเครื่องจักรรุ่นใหม่',
    description: 'เอกสารคู่มือการผลิตและการตรวจสอบคุณภาพที่ติดหน้างานเป็นเวอร์ชันเก่า ทำให้พนักงานใหม่เข้าใจขั้นตอนการสอบเทียบเซนเซอร์ผิดพลาดและเกิดของเสียในล็อตการผลิต',
    locationOrUnit: 'โรงงานผลิต สายการประกอบ 3',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'อนุชา รัตนเวช',
    submitterEmployeeId: 'EMP-6602',
    submitterDepartment: 'Manufacturing Quality Control',
    submitterEmail: 'anucha.r@company.internal',
    gatekeeperDepartment: 'Operational Excellence & Quality Assurance',
    assignedOfficerName: 'วิภาดา พรหมมาศ (QA Specialist)',
    assignedOfficerEmail: 'wiphada.p@company.internal',
    slaTargetHours: 48,
    slaDueDate: '2026-08-26T17:00:00.000Z',
    slaStatus: 'met',
    status: 'closed',
    urgency: 'Medium',
    riskSeverity: 'Moderate',
    sentiment: 'Concerned',
    clusterGroup: 'Process Standardization & SOP Maintenance',
    rootCauseCategory: 'Process',
    rootCauseSummary: 'ฝ่ายวิศวกรรมส่งมอบเครื่องจักรใหม่โดยยังไม่ได้อัปเดตเอกสารมาตรฐาน QA เข้าระบบ Document Control',
    preventiveActionPlan: 'บังคับใช้ Checklist การตรวจรับเครื่องจักรใหม่ ต้องมี SOP ภาษาไทยอนุมัติก่อนเริ่มการผลิต',
    resolutionSummary: 'ทีม QA ได้ทำการแก้ไขและพิมพ์ SOP ฉบับอัปเดต Rev.4 พร้อม QR Code วิดีโอสอนการใช้งานติดหน้างานเรียบร้อยแล้ว และจัด Briefing พนักงานประจำกะทุกคน',
    resolvedAt: '2026-08-26T15:00:00.000Z',
    closedAt: '2026-08-27T08:30:00.000Z',
    evaluation: {
      id: 'eval-2',
      ticketId: 'tk-7',
      overallScore: 4,
      speedRating: 4,
      resolutionQualityRating: 5,
      serviceMannerRating: 5,
      clarityRating: 4,
      isResolvedPermanently: true,
      feedbackComment: 'ทีม QA ดำเนินการแก้ไขได้รวดเร็วมาก มีการทำวิดีโอ QR Code ให้สแกนดูทำให้เข้าใจง่ายขึ้นมากครับ',
      improvementSuggestions: 'อยากให้มีการทบทวน SOP ของไลน์ 1 และ 2 เพิ่มเติมด้วยครับ',
      evaluatedAt: '2026-08-27T08:30:00.000Z',
    },
    attachments: [
      { id: 'att-9', name: 'sop_discrepancy_photo.jpg', size: '1.1 MB', type: 'image/jpeg' },
    ],
    timeline: [
      {
        id: 'tl-71',
        timestamp: '2026-08-24T08:30:00.000Z',
        actor: 'อนุชา รัตนเวช',
        actorRole: 'Employee',
        action: 'ส่งเรื่องแจ้งข้อบกพร่องเอกสาร QA',
        status: 'submitted',
      },
      {
        id: 'tl-72',
        timestamp: '2026-08-24T09:30:00.000Z',
        actor: 'QA Gatekeeper',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและอนุมัติใบแจ้งแก้ไขด่วน',
        status: 'gatekeeper_triaged',
      },
      {
        id: 'tl-73',
        timestamp: '2026-08-25T10:00:00.000Z',
        actor: 'วิภาดา พรหมมาศ',
        actorRole: 'Assigned Officer',
        action: 'จัดทำ SOP Rev.4 และทดสอบขั้นตอนจริงหน้างาน',
        status: 'in_progress',
      },
      {
        id: 'tl-74',
        timestamp: '2026-08-26T15:00:00.000Z',
        actor: 'วิภาดา พรหมมาศ',
        actorRole: 'Assigned Officer',
        action: 'ติดตั้ง SOP ใหม่และสรุปผลการแก้ไข',
        status: 'resolved',
      },
      {
        id: 'tl-75',
        timestamp: '2026-08-27T08:30:00.000Z',
        actor: 'อนุชา รัตนเวช',
        actorRole: 'Employee',
        action: 'ประเมินความพึงพอใจ 4 ดาวและปิดเรื่อง',
        status: 'closed',
      },
    ],
    createdAt: '2026-08-24T08:30:00.000Z',
    updatedAt: '2026-08-27T08:30:00.000Z',
  },
  {
    id: 'tk-8',
    trackingCode: 'TK-2026-0874',
    type: 'complaint',
    category: 'Ethics',
    title: 'ข้อร้องเรียนเรื่องการเลือกปฏิบัติในการจัดสรรกะการทำงานล่วงเวลา (OT)',
    description: 'หัวหน้ากะจัดสรรชั่วโมงโอทีให้เฉพาะกลุ่มคนสนิท ทำให้พนักงานคนอื่นเสียโอกาสในการสร้างรายได้เสริมอย่างไม่เป็นธรรมและขาดความโปร่งใส',
    locationOrUnit: 'ศูนย์กระจายสินค้าภาคกลาง',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'สุรศักดิ์ เมฆาวรรณ',
    submitterEmployeeId: 'EMP-6102',
    submitterDepartment: 'Distribution Operations',
    submitterEmail: 'surasak.m@company.internal',
    gatekeeperDepartment: 'Ethics Committee & Internal Governance',
    assignedOfficerName: 'รพีพร เกียรติภักดี (Employee Relations Specialist)',
    assignedOfficerEmail: 'rapeeporn.k@company.internal',
    slaTargetHours: 48,
    slaDueDate: '2026-08-28T15:00:00.000Z',
    slaStatus: 'on_track',
    status: 'in_progress',
    urgency: 'Medium',
    riskSeverity: 'Moderate',
    sentiment: 'Frustrated',
    clusterGroup: 'Workplace Fairness & Supervisory Conduct',
    rootCauseCategory: 'People',
    rootCauseSummary: 'ไม่มีระบบหมุนเวียนโควตา OT แบบดิจิทัล ใช้ดุลยพินิจของหัวหน้ากะแบบ manual',
    preventiveActionPlan: 'นำระบบ Auto-OT Allocation ในแอปพลิเคชันพนักงานมาใช้เพื่อความโปร่งใส 100%',
    attachments: [],
    timeline: [
      {
        id: 'tl-81',
        timestamp: '2026-08-26T13:00:00.000Z',
        actor: 'พนักงานผู้ขอสงวนนาม',
        actorRole: 'Employee',
        action: 'ยื่นเรื่องร้องเรียนด้านความเป็นธรรม',
        status: 'submitted',
      },
      {
        id: 'tl-82',
        timestamp: '2026-08-26T15:00:00.000Z',
        actor: 'Ethics Gatekeeper',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและตรวจสอบประวัติการลงเวลา OT ย้อนหลัง 3 เดือน',
        status: 'gatekeeper_triaged',
      },
      {
        id: 'tl-83',
        timestamp: '2026-08-27T10:00:00.000Z',
        actor: 'รพีพร เกียรติภักดี',
        actorRole: 'Assigned Officer',
        action: 'เรียกผู้จัดการศูนย์เข้าชี้แจงและตรวจสอบข้อมูลสถิติ',
        status: 'in_progress',
      },
    ],
    createdAt: '2026-08-26T13:00:00.000Z',
    updatedAt: '2026-08-27T10:00:00.000Z',
  },
  {
    id: 'tk-9',
    trackingCode: 'TK-2026-0873',
    type: 'complaint',
    category: 'Compliance',
    title: 'การจัดเก็บข้อมูลลูกค้าบนกระดาษโดยไม่มีการทำลายตามมาตรฐาน PDPA',
    description: 'พบเอกสารสำเนาบัตรประชาชนและข้อมูลติดต่อของลูกค้าที่ทำธุรกรรมหน้าร้านสาขาวางทิ้งไว้ในกล่องไม่ได้ใส่ตู้ล็อค และยังไม่มีการทำลายตามระยะเวลาที่กำหนดในกฎหมายคุ้มครองข้อมูลส่วนบุคคล',
    locationOrUnit: 'สาขาบริการลูกค้า Central World',
    isDirectToExecutive: true,
    confidentiality: 'standard_named',
    submitterName: 'วิศรุต สุทธิศิริ',
    submitterEmployeeId: 'EMP-7811',
    submitterDepartment: 'Customer Experience & Retail',
    submitterEmail: 'wissarut.s@company.internal',
    gatekeeperDepartment: 'Governance, Risk & Compliance Division',
    assignedOfficerName: 'ธเนศ พงษ์ไพบูลย์ (Data Protection Officer - DPO)',
    assignedOfficerEmail: 'thanet.p@company.internal',
    slaTargetHours: 24,
    slaDueDate: '2026-08-27T14:00:00.000Z',
    slaStatus: 'met',
    status: 'resolved',
    urgency: 'High',
    riskSeverity: 'High',
    sentiment: 'Concerned',
    clusterGroup: 'Data Privacy & PDPA Compliance',
    rootCauseCategory: 'Policy/Governance',
    rootCauseSummary: 'สาขาไม่มีเครื่องทำลายเอกสาร (Shredder) ประจำจุด และขาดตู้เซฟเก็บเอกสารสำคัญ',
    preventiveActionPlan: 'จัดซื้อเครื่องทำลายเอกสาร Cross-Cut ระดับความปลอดภัย DIN Level 4 ประจำทุกสาขา และเปลี่ยนเป็น Digital e-KYC 100%',
    resolutionSummary: 'DPO ได้ส่งทีมเข้าเก็บรวบรวมเอกสารทั้งหมดนำไปทำลายตามมาตรฐานความปลอดภัย พร้อมติดตั้งตู้ล็อคเอกสาร และเปิดใช้งานระบบ Paperless e-KYC ที่สาขาเพื่อป้องกันข้อมูลรั่วไหลถาวร',
    resolvedAt: '2026-08-27T11:30:00.000Z',
    attachments: [
      { id: 'att-10', name: 'pdpa_paper_storage_log.pdf', size: '2.1 MB', type: 'application/pdf' },
    ],
    timeline: [
      {
        id: 'tl-91',
        timestamp: '2026-08-26T09:00:00.000Z',
        actor: 'วิศรุต สุทธิศิริ',
        actorRole: 'Employee',
        action: 'แจ้งเตือนความเสี่ยงด้าน PDPA ส่งตรงถึงผู้บริหาร',
        status: 'submitted',
      },
      {
        id: 'tl-92',
        timestamp: '2026-08-26T10:00:00.000Z',
        actor: 'Compliance Gatekeeper',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและเปิดมาตรการ Data Breach Prevention',
        status: 'gatekeeper_triaged',
      },
      {
        id: 'tl-93',
        timestamp: '2026-08-26T13:00:00.000Z',
        actor: 'ธเนศ พงษ์ไพบูลย์',
        actorRole: 'Assigned Officer',
        action: 'เข้าตรวจค้นและยึดเอกสารเข้าสู่ศูนย์ควบคุมความปลอดภัย',
        status: 'in_progress',
      },
      {
        id: 'tl-94',
        timestamp: '2026-08-27T11:30:00.000Z',
        actor: 'ธเนศ พงษ์ไพบูลย์',
        actorRole: 'Assigned Officer',
        action: 'ดำเนินการทำลายเอกสารและรายงาน DPO ปิดเคสความเสี่ยง',
        status: 'resolved',
      },
    ],
    createdAt: '2026-08-26T09:00:00.000Z',
    updatedAt: '2026-08-27T11:30:00.000Z',
  },
  {
    id: 'tk-10',
    trackingCode: 'TK-2026-0882',
    type: 'complaint',
    category: 'IT',
    title: 'ปัญหา Token 2FA ของระบบ ERP ล็อคบ่อยกระทบการบันทึกใบสั่งซื้อและปิดรอบบิล',
    description: 'พนักงานฝ่ายจัดซื้อและบัญชีพบปัญหา Session Timeout และ Token 2FA ล็อคทุก 15 นาที ทำให้ต้องโทรแจ้ง IT ปลดล็อควันละกว่า 10 รอบ',
    locationOrUnit: 'สำนักงานใหญ่ ชั้น 14 ฝ่ายการเงินและจัดซื้อ',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'สุพรรณษา สิทธิโชค',
    submitterEmployeeId: 'EMP-4105',
    submitterDepartment: 'Finance & Accounting',
    submitterEmail: 'supansa.s@company.internal',
    gatekeeperDepartment: 'Digital Technology & Enterprise IT',
    slaTargetHours: 24,
    slaDueDate: '2026-09-02T12:00:00.000Z',
    slaStatus: 'on_track',
    status: 'submitted',
    urgency: 'High',
    riskSeverity: 'Moderate',
    sentiment: 'Frustrated',
    clusterGroup: 'IT Infrastructure & Authentication',
    attachments: [],
    timeline: [
      {
        id: 'tl-101',
        timestamp: '2026-08-31T14:20:00.000Z',
        actor: 'สุพรรณษา สิทธิโชค',
        actorRole: 'Employee',
        action: 'ยื่นคำร้องขอตรวจสอบระบบยืนยันตัวตน',
        status: 'submitted',
        notes: 'ส่งเรื่องเข้าสู่ระบบ Gatekeeper รอการจัดสรรเจ้าหน้าที่',
      },
    ],
    createdAt: '2026-08-31T14:20:00.000Z',
    updatedAt: '2026-08-31T14:20:00.000Z',
  },
  {
    id: 'tk-11',
    trackingCode: 'TK-2026-0883',
    type: 'complaint',
    category: 'HR',
    title: 'สอบถามความชัดเจนเรื่องสิทธิการเบิกค่ารักษาพยาบาลกรณีพบแพทย์เฉพาะทางนอกเวลา',
    description: 'เอกสารคู่มือสวัสดิการระบุไม่ชัดเจนเกี่ยวกับการเบิกจ่ายคลินิกพิเศษนอกเวลาของโรงพยาบาลรัฐ ทำให้พนักงานถูกตีกลับเอกสารขอเบิก',
    locationOrUnit: 'Corporate HR Services',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'กานต์นภัส รัตนวิบูลย์',
    submitterEmployeeId: 'EMP-2290',
    submitterDepartment: 'Customer Experience Operations',
    submitterEmail: 'kannapat.r@company.internal',
    gatekeeperDepartment: 'People & Culture Department',
    slaTargetHours: 48,
    slaDueDate: '2026-09-03T10:00:00.000Z',
    slaStatus: 'on_track',
    status: 'submitted',
    urgency: 'Medium',
    riskSeverity: 'Low',
    sentiment: 'Concerned',
    clusterGroup: 'Medical Benefits & Policy Clarification',
    attachments: [],
    timeline: [
      {
        id: 'tl-111',
        timestamp: '2026-08-31T15:00:00.000Z',
        actor: 'กานต์นภัส รัตนวิบูลย์',
        actorRole: 'Employee',
        action: 'ยื่นคำร้องขอคำชี้แจงระเบียบสวัสดิการ',
        status: 'submitted',
        notes: 'รอฝ่าย HR ประจำแผนกรับเรื่องเพื่อตรวจสอบระเบียบการเบิกจ่าย',
      },
    ],
    createdAt: '2026-08-31T15:00:00.000Z',
    updatedAt: '2026-08-31T15:00:00.000Z',
  },
  {
    id: 'tk-12',
    trackingCode: 'TK-2026-0884',
    type: 'suggestion',
    category: 'HR',
    title: 'ข้อเสนอแนะ: ขยายเวลาเปิดให้บริการห้องพยาบาลประจำโรงงานช่วงกะดึก',
    description: 'พนักงานฝ่ายผลิตกะดึก (20:00 - 08:00) ขอเสนอให้มีพยาบาลวิชาชีพหรือเจ้าหน้าที่ปฐมพยาบาลประจำการตลอด 24 ชั่วโมง เพื่อรองรับเหตุเจ็บป่วยฉุกเฉิน',
    locationOrUnit: 'โรงงานระยอง โซนพยาบาลอาคาร 1',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'พิเชษฐ์ เลิศวณิชย์',
    submitterEmployeeId: 'EMP-5512',
    submitterDepartment: 'Plant Operations & Manufacturing',
    submitterEmail: 'pichet.l@company.internal',
    gatekeeperDepartment: 'People & Culture Department',
    slaTargetHours: 72,
    slaDueDate: '2026-09-04T17:00:00.000Z',
    slaStatus: 'on_track',
    status: 'submitted',
    urgency: 'Medium',
    riskSeverity: 'Moderate',
    sentiment: 'Constructive',
    clusterGroup: 'Employee Health & Clinic Accessibility',
    attachments: [],
    timeline: [
      {
        id: 'tl-121',
        timestamp: '2026-08-31T16:10:00.000Z',
        actor: 'พิเชษฐ์ เลิศวณิชย์',
        actorRole: 'Employee',
        action: 'ยื่นข้อเสนอแนะพัฒนาห้องพยาบาล',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T16:10:00.000Z',
    updatedAt: '2026-08-31T16:10:00.000Z',
  },
  {
    id: 'tk-13',
    trackingCode: 'TK-2026-0885',
    type: 'complaint',
    category: 'Safety',
    title: 'ไฟส่องสว่างบริเวณลานจอดรถพนักงานด้านหลังอาคาร 2 ชำรุดดับหลายจุด เสี่ยงต่อความปลอดภัยในกะดึก',
    description: 'เสาไฟทางเดินและลานจอดรถจักรยานยนต์ดับมืดตั้งแต่เวลา 19:00 น. ทางเดินค่อนข้างเปลี่ยวและมีจุดอับสายตา',
    locationOrUnit: 'ลานจอดรถจักรยานยนต์ ท้ายอาคาร 2',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'ธิดารัตน์ รุ่งเรือง',
    submitterEmployeeId: 'EMP-3801',
    submitterDepartment: 'Warehouse & Logistics',
    submitterEmail: 'thidarat.r@company.internal',
    gatekeeperDepartment: 'Occupational Health & Safety Office',
    slaTargetHours: 24,
    slaDueDate: '2026-09-01T20:00:00.000Z',
    slaStatus: 'on_track',
    status: 'submitted',
    urgency: 'High',
    riskSeverity: 'Moderate',
    sentiment: 'Concerned',
    clusterGroup: 'Workplace Physical Security & Lighting',
    attachments: [],
    timeline: [
      {
        id: 'tl-131',
        timestamp: '2026-08-31T17:30:00.000Z',
        actor: 'ธิดารัตน์ รุ่งเรือง',
        actorRole: 'Employee',
        action: 'แจ้งจุดเสี่ยงด้านความปลอดภัย',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T17:30:00.000Z',
    updatedAt: '2026-08-31T17:30:00.000Z',
  },
  {
    id: 'tk-14',
    trackingCode: 'TK-2026-0886',
    type: 'complaint',
    category: 'Compliance',
    title: 'ข้อหารือเรื่องแนวปฏิบัติการส่งข้อมูลพนักงานให้คู่ค้าภายนอกตามเกณฑ์ PDPA',
    description: 'ฝ่ายการตลาดต้องการส่งรายชื่อผู้ร่วมงานสัมมนาให้ผู้จัดงานภายนอก ขอคำแนะนำและแบบฟอร์ม Data Sharing Agreement',
    locationOrUnit: 'ฝ่ายการตลาดและการสื่อสารองค์กร',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'ปวีณ์กร มิ่งขวัญ',
    submitterEmployeeId: 'EMP-4991',
    submitterDepartment: 'Marketing & Brand Strategy',
    submitterEmail: 'paweekorn.m@company.internal',
    gatekeeperDepartment: 'Governance, Risk & Compliance Division',
    slaTargetHours: 48,
    slaDueDate: '2026-09-03T14:00:00.000Z',
    slaStatus: 'on_track',
    status: 'submitted',
    urgency: 'Medium',
    riskSeverity: 'Low',
    sentiment: 'Constructive',
    clusterGroup: 'Data Sharing Agreements & PDPA Compliance',
    attachments: [],
    timeline: [
      {
        id: 'tl-141',
        timestamp: '2026-08-31T18:00:00.000Z',
        actor: 'ปวีณ์กร มิ่งขวัญ',
        actorRole: 'Employee',
        action: 'ยื่นคำขอรับคำปรึกษาด้านกฎเกณฑ์',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T18:00:00.000Z',
    updatedAt: '2026-08-31T18:00:00.000Z',
  },
  {
    id: 'tk-15',
    trackingCode: 'TK-2026-0887',
    type: 'complaint',
    category: 'Ethics',
    title: 'ข้อร้องเรียนเรื่องการรับของขวัญมูลค่าสูงและเลี้ยงสังสรรค์ช่วงเทศกาลจากคู่ค้าผู้ประมูลงาน',
    description: 'พบข้อมูลว่ามีกรรมการตรวจรับงานเข้าร่วมงานเลี้ยงสังสรรค์ส่วนตัวที่จัดโดยผู้รับเหมารายใหญ่ที่อยู่ระหว่างขั้นตอนการประมูลคัดเลือก',
    locationOrUnit: 'ฝ่ายจัดซื้อและวิศวกรรมโครงการ',
    isDirectToExecutive: true,
    confidentiality: 'confidential_restricted',
    submitterName: 'พนักงานผู้แจ้งเบาะแส (ไม่เปิดเผยชื่อ)',
    gatekeeperDepartment: 'Ethics Committee & Internal Governance',
    slaTargetHours: 24,
    slaDueDate: '2026-09-01T22:00:00.000Z',
    slaStatus: 'on_track',
    status: 'submitted',
    urgency: 'Critical',
    riskSeverity: 'Severe',
    sentiment: 'Urgent',
    clusterGroup: 'Conflict of Interest & Gift Policy Violation',
    attachments: [],
    timeline: [
      {
        id: 'tl-151',
        timestamp: '2026-08-31T19:15:00.000Z',
        actor: 'ผู้แจ้งเบาะแส',
        actorRole: 'Employee',
        action: 'แจ้งเบาะแสจริยธรรมส่งตรงถึง CEO/EVP',
        status: 'submitted',
        notes: 'เลือกช่องทางส่งตรง CEO เนื่องจากผู้ถูกร้องเป็นหัวหน้าแผนก',
      },
    ],
    createdAt: '2026-08-31T19:15:00.000Z',
    updatedAt: '2026-08-31T19:15:00.000Z',
  },
  {
    id: 'tk-16',
    trackingCode: 'TK-2026-0888',
    type: 'complaint',
    category: 'Harassment',
    title: 'พฤติกรรมการใช้วาจาข่มขู่คุกคามและการเลือกปฏิบัติในแผนกงานอย่างต่อเนื่อง',
    description: 'พนักงานในทีมถูกผู้จัดการกดดันด้วยถ้อยคำหยาบคาย และข่มขู่ว่าจะไม่ผ่านการทดลองงานหากไม่ยอมทำงานนอกเวลาโดยไม่บันทึกโอที',
    locationOrUnit: 'ศูนย์กระจายสินค้าภาคตะวันออกเฉียงเหนือ',
    isDirectToExecutive: true,
    confidentiality: 'confidential_restricted',
    submitterName: 'พนักงานผู้ได้รับผลกระทบ',
    gatekeeperDepartment: 'Employee Grievance & Whistleblower Panel',
    slaTargetHours: 12,
    slaDueDate: '2026-09-01T10:00:00.000Z',
    slaStatus: 'on_track',
    status: 'submitted',
    urgency: 'Critical',
    riskSeverity: 'Severe',
    sentiment: 'Frustrated',
    clusterGroup: 'Workplace Psychological Safety & Anti-Bullying',
    attachments: [],
    timeline: [
      {
        id: 'tl-161',
        timestamp: '2026-08-31T20:00:00.000Z',
        actor: 'ผู้ร้องเรียน',
        actorRole: 'Employee',
        action: 'ยื่นคำร้องเรียนฉุกเฉินส่งตรงคณะกรรมการคุ้มครองสิทธิ์',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T20:00:00.000Z',
    updatedAt: '2026-08-31T20:00:00.000Z',
  },
  {
    id: 'tk-17',
    trackingCode: 'TK-2026-0889',
    type: 'complaint',
    category: 'Fraud',
    title: 'ข้อสงสัยเกี่ยวกับการอนุมัติเบิกจ่ายค่าเดินทางและเบี้ยเลี้ยงซ้ำซ้อนในโครงการต่างจังหวัด',
    description: 'ตรวจสอบพบใบเสร็จค่าน้ำมันและโรงแรมที่ซ้ำกับใบเบิกของอีกทีมในวันและเวลาเดียวกัน ยอดรวมกว่า 180,000 บาท',
    locationOrUnit: 'ฝ่ายบริหารโครงการภาคเหนือ',
    isDirectToExecutive: true,
    confidentiality: 'confidential_restricted',
    submitterName: 'ผู้ตรวจสอบภายใน',
    gatekeeperDepartment: 'Internal Audit & Forensic Investigation',
    slaTargetHours: 24,
    slaDueDate: '2026-09-01T23:00:00.000Z',
    slaStatus: 'on_track',
    status: 'submitted',
    urgency: 'Critical',
    riskSeverity: 'Severe',
    sentiment: 'Urgent',
    clusterGroup: 'Expense Claim Integrity & Fraud Audit',
    attachments: [],
    timeline: [
      {
        id: 'tl-171',
        timestamp: '2026-08-31T21:10:00.000Z',
        actor: 'ผู้แจ้งเบาะแส',
        actorRole: 'Employee',
        action: 'ส่งเรื่องแจ้งข้อสงสัยทุจริตตรงถึงบอร์ดบริหาร',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T21:10:00.000Z',
    updatedAt: '2026-08-31T21:10:00.000Z',
  },
  {
    id: 'tk-18',
    trackingCode: 'TK-2026-0890',
    type: 'complaint',
    category: 'Quality',
    title: 'อุปกรณ์ตรวจวัด Caliper ในแผนก QA ไลน์ 2 มีค่าเบี่ยงเบนเกินเกณฑ์มาตรฐาน ISO',
    description: 'อุปกรณ์เวอร์เนียร์คาลิปเปอร์ 4 ตัวที่ใช้ในไลน์ตรวจสอบชิ้นงานแม่พิมพ์ส่งผลการวัดคลาดเคลื่อน 0.05 mm จำเป็นต้องส่งสอบเทียบด่วน',
    locationOrUnit: 'โรงงานแปรรูปชิ้นส่วน ไลน์ QC-02',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'สมชาย บุญชู',
    submitterEmployeeId: 'EMP-7120',
    submitterDepartment: 'Quality Assurance & Metrology',
    submitterEmail: 'somchai.b@company.internal',
    gatekeeperDepartment: 'Operational Excellence & Quality Assurance',
    slaTargetHours: 24,
    slaDueDate: '2026-09-01T23:30:00.000Z',
    slaStatus: 'on_track',
    status: 'submitted',
    urgency: 'High',
    riskSeverity: 'Moderate',
    sentiment: 'Concerned',
    clusterGroup: 'Calibration & Measurement Tool Accuracy',
    attachments: [],
    timeline: [
      {
        id: 'tl-181',
        timestamp: '2026-08-31T21:40:00.000Z',
        actor: 'สมชาย บุญชู',
        actorRole: 'Employee',
        action: 'ส่งแจ้งเตือนเครื่องมือวัดไม่ได้มาตรฐาน',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T21:40:00.000Z',
    updatedAt: '2026-08-31T21:40:00.000Z',
  },
  {
    id: 'tk-19',
    trackingCode: 'TK-2026-0891',
    type: 'complaint',
    category: 'Environment',
    title: 'ปัญหากลิ่นสารเคมีและเสียงรบกวนจากบ่อบำบัดน้ำเสียส่วนขยายใกล้โซนโรงอาหาร',
    description: 'ช่วงเวลา 11:30 - 13:00 น. มีกลิ่นกำมะถันรุนแรงพัดเข้ามายังโรงอาหารพนักงาน ขอให้ฝ่ายสิ่งแวดล้อมตรวจเช็คระบบ Bio-filter และพัดลมดูดอากาศ',
    locationOrUnit: 'โรงอาหารกลาง และบ่อบำบัดน้ำเสียแปลงใต้',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'วาสนา กลิ่นสุคนธ์',
    submitterEmployeeId: 'EMP-3318',
    submitterDepartment: 'Administrative Services',
    submitterEmail: 'wassana.k@company.internal',
    gatekeeperDepartment: 'Sustainability & Environmental Safety Team',
    slaTargetHours: 24,
    slaDueDate: '2026-09-02T10:00:00.000Z',
    slaStatus: 'on_track',
    status: 'submitted',
    urgency: 'Medium',
    riskSeverity: 'Moderate',
    sentiment: 'Frustrated',
    clusterGroup: 'Odor Control & Wastewater Treatment System',
    attachments: [],
    timeline: [
      {
        id: 'tl-191',
        timestamp: '2026-08-31T22:00:00.000Z',
        actor: 'วาสนา กลิ่นสุคนธ์',
        actorRole: 'Employee',
        action: 'ส่งเรื่องร้องเรียนกลิ่นรบกวนโรงอาหาร',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T22:00:00.000Z',
    updatedAt: '2026-08-31T22:00:00.000Z',
  },
  {
    id: 'tk-20',
    trackingCode: 'TK-2026-0892',
    type: 'complaint',
    category: 'IT',
    title: 'จอแสดงผลและพอร์ต HDMI ห้องประชุม Boardroom 402 ภาพกระพริบไม่สามารถเชื่อมต่อได้',
    description: 'สายเชื่อมต่อ HDMI และ Adapter Type-C ชำรุด ภาพขึ้นจอดำสลับติดๆ ดับๆ จำเป็นต้องเปลี่ยนอุปกรณ์ก่อนการประชุมผู้ถือหุ้นวันพุธนี้',
    locationOrUnit: 'อาคาร A ชั้น 4 ห้องประชุม Boardroom 402',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'กิตติคุณ เจริญศิลป์',
    submitterEmployeeId: 'EMP-1099',
    submitterDepartment: 'Corporate Secretary & Board Office',
    submitterEmail: 'kittikun.c@company.internal',
    gatekeeperDepartment: 'Digital Technology & Enterprise IT',
    slaTargetHours: 12,
    slaDueDate: '2026-09-01T12:00:00.000Z',
    slaStatus: 'on_track',
    status: 'submitted',
    urgency: 'High',
    riskSeverity: 'Moderate',
    sentiment: 'Urgent',
    clusterGroup: 'Meeting Room Audio/Visual & Hardware',
    attachments: [],
    timeline: [
      {
        id: 'tl-201',
        timestamp: '2026-08-31T22:30:00.000Z',
        actor: 'กิตติคุณ เจริญศิลป์',
        actorRole: 'Employee',
        action: 'ส่งเรื่องขอเปลี่ยนอุปกรณ์เชื่อมต่อห้องประชุมด่วน',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T22:30:00.000Z',
    updatedAt: '2026-08-31T22:30:00.000Z',
  },
];

export const INITIAL_GATEKEEPER_CONFIGS: Record<GrievanceCategory, DepartmentGatekeeperConfig> = {
  HR: {
    category: 'HR',
    departmentName: 'People & Culture Department (ฝ่ายบริหารทรัพยากรบุคคล)',
    departmentCode: 'DEPT-HR-01',
    defaultSlaHours: 48,
    leadOfficer: {
      id: 'usr-hr-1',
      name: 'ชลธิชา เกียรติวรานนท์',
      email: 'chonthicha.k@company.internal',
      roleTitle: 'Head of People Partnering & ER',
      isLead: true,
      phone: '02-555-1101',
    },
    officers: [
      {
        id: 'usr-hr-1',
        name: 'ชลธิชา เกียรติวรานนท์',
        email: 'chonthicha.k@company.internal',
        roleTitle: 'Head of People Partnering & ER',
        isLead: true,
        phone: '02-555-1101',
      },
      {
        id: 'usr-hr-2',
        name: 'รพีพร เกียรติภักดี',
        email: 'rapeeporn.k@company.internal',
        roleTitle: 'Employee Relations Specialist',
        isLead: false,
        phone: '02-555-1102',
      },
      {
        id: 'usr-hr-3',
        name: 'ธนกฤต สิทธิพงศ์',
        email: 'thanakrit.s@company.internal',
        roleTitle: 'Talent & Compensation Lead',
        isLead: false,
        phone: '02-555-1103',
      },
    ],
    autoAssignMode: 'round_robin',
    escalationEmail: 'hr.escalation@company.internal',
    updatedAt: '2026-08-25T10:00:00.000Z',
  },
  IT: {
    category: 'IT',
    departmentName: 'Digital Technology & Enterprise IT (ฝ่ายเทคโนโลยีสารสนเทศ)',
    departmentCode: 'DEPT-IT-02',
    defaultSlaHours: 24,
    leadOfficer: {
      id: 'usr-it-1',
      name: 'กิตติศักดิ์ ชัยชนะ',
      email: 'kittisak.c@company.internal',
      roleTitle: 'Lead IT Network & Infrastructure',
      isLead: true,
      phone: '02-555-2201',
    },
    officers: [
      {
        id: 'usr-it-1',
        name: 'กิตติศักดิ์ ชัยชนะ',
        email: 'kittisak.c@company.internal',
        roleTitle: 'Lead IT Network & Infrastructure',
        isLead: true,
        phone: '02-555-2201',
      },
      {
        id: 'usr-it-2',
        name: 'อนุชา ฤทธิ์ธาดา',
        email: 'anucha.r@company.internal',
        roleTitle: 'Senior System & Cloud Administrator',
        isLead: false,
        phone: '02-555-2202',
      },
      {
        id: 'usr-it-3',
        name: 'ศิรดา ปรีชาญ',
        email: 'sirada.p@company.internal',
        roleTitle: 'IT Security & Access Control Officer',
        isLead: false,
        phone: '02-555-2203',
      },
    ],
    autoAssignMode: 'workload_balanced',
    escalationEmail: 'it.alert@company.internal',
    updatedAt: '2026-08-26T08:30:00.000Z',
  },
  Safety: {
    category: 'Safety',
    departmentName: 'Occupational Health & Safety Office (ฝ่ายความปลอดภัยและอาชีวอนามัย)',
    departmentCode: 'DEPT-EHS-03',
    defaultSlaHours: 24,
    leadOfficer: {
      id: 'usr-ehs-1',
      name: 'ประเสริฐ รุ่งโรจน์วิวัฒน์',
      email: 'prasert.r@company.internal',
      roleTitle: 'Chief Safety Officer (จป.วิชาชีพ)',
      isLead: true,
      phone: '02-555-3301',
    },
    officers: [
      {
        id: 'usr-ehs-1',
        name: 'ประเสริฐ รุ่งโรจน์วิวัฒน์',
        email: 'prasert.r@company.internal',
        roleTitle: 'Chief Safety Officer (จป.วิชาชีพ)',
        isLead: true,
        phone: '02-555-3301',
      },
      {
        id: 'usr-ehs-2',
        name: 'วิภาดา วาทิตา',
        email: 'vipada.w@company.internal',
        roleTitle: 'Building & Facility Safety Engineer',
        isLead: false,
        phone: '02-555-3302',
      },
    ],
    autoAssignMode: 'lead_manual',
    escalationEmail: 'safety.emergency@company.internal',
    updatedAt: '2026-08-24T14:00:00.000Z',
  },
  Compliance: {
    category: 'Compliance',
    departmentName: 'Governance, Risk & Compliance Division (ฝ่ายกำกับดูแลและกฎหมาย)',
    departmentCode: 'DEPT-GRC-04',
    defaultSlaHours: 48,
    leadOfficer: {
      id: 'usr-grc-1',
      name: 'กานต์รวี ธรรมศาสตร์',
      email: 'karnrawee.t@company.internal',
      roleTitle: 'Data Protection Officer (DPO) & Legal Lead',
      isLead: true,
      phone: '02-555-4401',
    },
    officers: [
      {
        id: 'usr-grc-1',
        name: 'กานต์รวี ธรรมศาสตร์',
        email: 'karnrawee.t@company.internal',
        roleTitle: 'Data Protection Officer (DPO) & Legal Lead',
        isLead: true,
        phone: '02-555-4401',
      },
      {
        id: 'usr-grc-2',
        name: 'นิติกรอาวุโส มนตรี ธนบดีกุล',
        email: 'montri.t@company.internal',
        roleTitle: 'Senior Legal & Regulatory Counsel',
        isLead: false,
        phone: '02-555-4402',
      },
    ],
    autoAssignMode: 'lead_manual',
    escalationEmail: 'dpo.compliance@company.internal',
    updatedAt: '2026-08-25T11:00:00.000Z',
  },
  Ethics: {
    category: 'Ethics',
    departmentName: 'Ethics Committee & Internal Governance (คณะกรรมการจริยธรรมองค์กร)',
    departmentCode: 'DEPT-ETH-05',
    defaultSlaHours: 72,
    leadOfficer: {
      id: 'usr-eth-1',
      name: 'ศ.พิเศษ พิทักษ์ สัตยบุตร',
      email: 'pitak.s@company.internal',
      roleTitle: 'Chair of Ethics Review Board',
      isLead: true,
      phone: '02-555-5501',
    },
    officers: [
      {
        id: 'usr-eth-1',
        name: 'ศ.พิเศษ พิทักษ์ สัตยบุตร',
        email: 'pitak.s@company.internal',
        roleTitle: 'Chair of Ethics Review Board',
        isLead: true,
        phone: '02-555-5501',
      },
      {
        id: 'usr-eth-2',
        name: 'นภาพร วรวิทย์',
        email: 'naphaporn.w@company.internal',
        roleTitle: 'Ethics Officer & Ombudsman Secretarial',
        isLead: false,
        phone: '02-555-5502',
      },
    ],
    autoAssignMode: 'lead_manual',
    escalationEmail: 'ethics.board@company.internal',
    updatedAt: '2026-08-20T09:00:00.000Z',
  },
  Harassment: {
    category: 'Harassment',
    departmentName: 'Employee Grievance & Whistleblower Panel (คณะกรรมการคุ้มครองสิทธิพนักงาน)',
    departmentCode: 'DEPT-HRM-06',
    defaultSlaHours: 24,
    leadOfficer: {
      id: 'usr-hrm-1',
      name: 'มนตรี ธนบดีกุล',
      email: 'montri.t@company.internal',
      roleTitle: 'Senior Legal & Whistleblower Protection Lead',
      isLead: true,
      phone: '02-555-6601',
    },
    officers: [
      {
        id: 'usr-hrm-1',
        name: 'มนตรี ธนบดีกุล',
        email: 'montri.t@company.internal',
        roleTitle: 'Senior Legal & Whistleblower Protection Lead',
        isLead: true,
        phone: '02-555-6601',
      },
      {
        id: 'usr-hrm-2',
        name: 'พญ. พรรณนิภา จิตตพัฒน์',
        email: 'phannipha.j@company.internal',
        roleTitle: 'Corporate Psychologist & Counselor',
        isLead: false,
        phone: '02-555-6602',
      },
    ],
    autoAssignMode: 'lead_manual',
    escalationEmail: 'whistleblower.safe@company.internal',
    updatedAt: '2026-08-26T16:00:00.000Z',
  },
  Fraud: {
    category: 'Fraud',
    departmentName: 'Internal Audit & Forensic Investigation (ฝ่ายตรวจสอบภายในและการสอบสวน)',
    departmentCode: 'DEPT-AUD-07',
    defaultSlaHours: 24,
    leadOfficer: {
      id: 'usr-aud-1',
      name: 'วรพจน์ ปิยะปัญญา',
      email: 'worapoj.p@company.internal',
      roleTitle: 'Director of Forensic Audit & Financial Investigation',
      isLead: true,
      phone: '02-555-7701',
    },
    officers: [
      {
        id: 'usr-aud-1',
        name: 'วรพจน์ ปิยะปัญญา',
        email: 'worapoj.p@company.internal',
        roleTitle: 'Director of Forensic Audit & Financial Investigation',
        isLead: true,
        phone: '02-555-7701',
      },
      {
        id: 'usr-aud-2',
        name: 'ธีรดนย์ รัตนเมธา',
        email: 'theeradon.r@company.internal',
        roleTitle: 'Senior Financial Auditor (CIA, CFE)',
        isLead: false,
        phone: '02-555-7702',
      },
    ],
    autoAssignMode: 'lead_manual',
    escalationEmail: 'forensic.audit@company.internal',
    updatedAt: '2026-08-27T08:00:00.000Z',
  },
  Quality: {
    category: 'Quality',
    departmentName: 'Operational Excellence & Quality Assurance (ฝ่ายประกันคุณภาพและการปรับปรุง)',
    departmentCode: 'DEPT-QA-08',
    defaultSlaHours: 48,
    leadOfficer: {
      id: 'usr-qa-1',
      name: 'วิศรุต สินธพวัฒน์',
      email: 'wisarut.s@company.internal',
      roleTitle: 'Quality Assurance & Lean Process Manager',
      isLead: true,
      phone: '02-555-8801',
    },
    officers: [
      {
        id: 'usr-qa-1',
        name: 'วิศรุต สินธพวัฒน์',
        email: 'wisarut.s@company.internal',
        roleTitle: 'Quality Assurance & Lean Process Manager',
        isLead: true,
        phone: '02-555-8801',
      },
      {
        id: 'usr-qa-2',
        name: 'นลินี วรพงษ์',
        email: 'nalinee.w@company.internal',
        roleTitle: 'Service Quality Auditor',
        isLead: false,
        phone: '02-555-8802',
      },
    ],
    autoAssignMode: 'round_robin',
    escalationEmail: 'qa.feedback@company.internal',
    updatedAt: '2026-08-23T10:00:00.000Z',
  },
  Environment: {
    category: 'Environment',
    departmentName: 'Sustainability & Environmental Safety Team (ฝ่ายความยั่งยืนและสิ่งแวดล้อม ESG)',
    departmentCode: 'DEPT-ESG-09',
    defaultSlaHours: 48,
    leadOfficer: {
      id: 'usr-esg-1',
      name: 'ดร. ภาสกร วงศ์สุวรรณ',
      email: 'passakorn.w@company.internal',
      roleTitle: 'ESG & Environmental Lead',
      isLead: true,
      phone: '02-555-9901',
    },
    officers: [
      {
        id: 'usr-esg-1',
        name: 'ดร. ภาสกร วงศ์สุวรรณ',
        email: 'passakorn.w@company.internal',
        roleTitle: 'ESG & Environmental Lead',
        isLead: true,
        phone: '02-555-9901',
      },
      {
        id: 'usr-esg-2',
        name: 'ปิยวรรณ เชษฐวิทย์',
        email: 'piyawan.c@company.internal',
        roleTitle: 'Energy & Carbon Footprint Analyst',
        isLead: false,
        phone: '02-555-9902',
      },
    ],
    autoAssignMode: 'round_robin',
    escalationEmail: 'esg.sustainability@company.internal',
    updatedAt: '2026-08-22T14:30:00.000Z',
  },
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    ticketId: 'tk-2',
    trackingCode: 'TK-2026-0880',
    title: 'แก้ไขเสร็จสิ้น: ปัญหาบันไดหนีไฟฉุกเฉิน',
    message: 'หน่วยงาน EHS ได้ทำการเคลียร์สิ่งกีดขวางเรียบร้อยแล้ว กรุณาเข้าประเมินความพึงพอใจการให้บริการ',
    timestamp: '2026-08-27T15:45:00.000Z',
    read: false,
    type: 'satisfaction_pending',
    recipientRole: 'employee',
  },
  {
    id: 'notif-2',
    ticketId: 'tk-1',
    trackingCode: 'TK-2026-0881',
    title: 'อัปเดตสถานะ: ปัญหาเครือข่าย Wi-Fi ชั้น 18',
    message: 'วิศวกรโครงข่ายไอที (กิตติศักดิ์ ชัยชนะ) เริ่มเข้าดำเนินการตรวจสอบและปรับแต่ง Access Point แล้ว',
    timestamp: '2026-08-27T13:00:00.000Z',
    read: false,
    type: 'status_update',
    recipientRole: 'employee',
  },
  {
    id: 'notif-3',
    ticketId: 'tk-4',
    trackingCode: 'TK-2026-0878',
    title: 'แจ้งเตือนผู้บริหาร: ได้รับข้อร้องเรียนส่งตรงถึง CEO/EVP',
    message: 'มีข้อร้องเรียนหมวดหมู่ Harassment ระดับความเร่งด่วนสูง ยื่นเรื่องส่งตรงถึงผู้บริหารระดับสูง',
    timestamp: '2026-08-26T16:00:00.000Z',
    read: true,
    type: 'direct_ceo_alert',
    recipientRole: 'executive',
  },
  {
    id: 'notif-4',
    ticketId: 'tk-9',
    trackingCode: 'TK-2026-0873',
    title: 'แก้ไขเสร็จสิ้น: รายงานความเสี่ยง PDPA สาขา Central World',
    message: 'ฝ่าย Compliance & DPO ได้แก้ไขและทำลายเอกสารเสร็จสมบูรณ์แล้ว',
    timestamp: '2026-08-27T11:30:00.000Z',
    read: true,
    type: 'status_update',
    recipientRole: 'employee',
  },
];
